# Numpy

#### Importing Numpy

To import an external Python library such as Numpy, use Python's import function. To save yourself some typing later on, you can give the library you import an alias. Here, we are importing Numpy and giving it an alias of np.

In [ ]:
import numpy as np

### Creating numpy array

# 1-D Array

In [ ]:
#The np.array function is used to create an array

#creating a 1 dimensional array

x = np.array([1, 2, 3, 4, 5]) 
x

array([1, 2, 3, 4, 5])

In [ ]:
#The shape property is usually used to get the current shape of an array
x.shape


(5,)

# 2-D Array

In [ ]:
# Creating a 2D arrays  
y = np.array([[1, 2], [3, 4], [5,6]]) 
y

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
y.shape

(2, 2)

# 3-D Arrays

In [ ]:
# Creating a 3D arrays  
z = np.array([[(1, 2), (3, 4)], [(5, 6), (7, 8)]]) 
z

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
z.shape

(2, 2, 2)

# Numpy function

In [ ]:
#Numpy has built-in functions for creating arrays and manipulating.
#arange is Used to create arrays with values in a specified range.
A = np.arange(25)
A

In [ ]:
#To change the shape of an array
B = A.reshape(25,1)
C = B.reshape(5,5)
C

* Note: Before a reshape function will run successful, the multiplication of the two parameter supply to the function must be equal with multiplication of the shape of the original array you want to reshape.
For example: The shape of variable B is (25, 1) therefore 25 * 1 = 25
The two parameter supply to the reshape function is (5, 5), 5 * 5 = 25



In [ ]:
#zeros is used to create an array filled with zeros. 
#ones is used to create an array filled with ones
#random.randn is used to create an array filled with random normal entries

#1D array
np.zeros (3)
np.ones (3)
np.random.randn (3)

In [ ]:
#2D array
np.zeros((2,5))
#np.ones ((2,5))
#np.random.randn ((2,5))

### Accessing elements of numpy array

In [ ]:
#To access an element in a two-dimensional array, you need to specify an index for both the row and the column.
D = np.array([[5, 7, 8],[3, 5, 9]])
D

array([[5, 7, 8],
       [3, 5, 9]])

In [ ]:
# note that for array numbering in numpy, it starts from zero
#Row 1, column 0 gives a scalar value
D[1,0]

3

In [ ]:
#Row 1, column 2
D[1,2]happy meme template

9

### Basic Numpy Array Math Operations

In [ ]:
s = np.array([[1,2,3],[4,5,6]])
t = np.array([[2,2,2],[3,3,3]])

#Transpose a matrix
s.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#Elementwise addittion
np.add(s,t)

array([[3, 4, 5],
       [7, 8, 9]])

In [ ]:
#Elementwise Subtraction
np.subtract(s,t)

array([[-1,  0,  1],
       [ 1,  2,  3]])

In [ ]:
#Elementwise Multiplication
np.multiply(s,t)

array([[ 2,  4,  6],
       [12, 15, 18]])